# Generated by Django 3.2.2 on 2021-05-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=30)),
                ('book_type', models.CharField(choices=[('NOVEL', 'Novel'), ('ARTICLE', 'Article'), ('MAGZINE', 'Magzine'), ('NEWS', 'News')], max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('excerpt', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
